projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/blocs/CreateResourceBloc.kt, projects/sdk/dynamic/dynamic-host/src/main/java/com/tencent/shadow/dynamic/host/ChangeApkContextWrapper.java
=> fix crash: 索尼G3116，F3116 android 7.0机型兼容性问题。

projects/sample/sample-plugin/sample-app-lib/src/main/java/com/tencent/shadow/sample/plugin/app/lib/usecases/provider/TestFileProviderActivity.java
=> TestFileProviderActivity重建导致crash

projects/sdk/core/gradle-plugin/src/main/kotlin/com/tencent/shadow/core/gradle/ShadowPlugin.kt
=> 简化支持Android Plugin for Gradle 3.0.0的代码

projects/sample/source/sample-host-lib/src/main/java/com/tencent/shadow/sample/host/lib/LoadPluginCallback.java, projects/sample/source/sample-host/src/main/java/com/tencent/shadow/sample/host/PluginProcessPPS.java, projects/sample/source/sample-plugin/sample-loader/build.gradle, projects/sample/source/sample-plugin/sample-loader/src/main/java/com/tencent/shadow/dynamic/impl/WhiteList.java, projects/sample/source/sample-plugin/sample-loader/src/main/java/com/tencent/shadow/sample/plugin/loader/SamplePluginLoader.java, projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/ShadowPluginLoader.kt, projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/blocs/LoadPluginBloc.kt, projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/infos/PluginParts.kt
=> Hook load plugin

projects/sample/source/sample-plugin/sample-app-lib/src/main/AndroidManifest.xml, projects/sample/source/sample-plugin/sample-app-lib/src/main/java/com/tencent/shadow/sample/plugin/app/lib/gallery/cases/UseCaseManager.java, projects/sample/source/sample-plugin/sample-app-lib/src/main/java/com/tencent/shadow/sample/plugin/app/lib/usecases/activity/TestActivitySetTheme.java, projects/sample/source/sample-plugin/sample-app-lib/src/main/res/layout/layout_activity_settheme.xml, projects/sample/source/sample-plugin/sample-app-lib/src/main/res/values-v21/themes.xml, projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ShadowActivity.java
但是 setTheme 形如虚设，调用不成功。
应该怎么修复呢？
期待效果：
实际效果：
=> 一只刚上手的萌新 增加了一个 Activity 的 setTheme 测试用例

projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/UriConverter.java, projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/container/DelegateProviderHolder.java, projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/container/PluginContainerActivity.java
Update the DelegateProvider modifier from public to private as there already exist set method and add get method
=> Update the Modifier for DelegateProvider field

projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/delegates/ShadowActivityDelegate.kt, projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/PluginActivity.java, projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/container/HostActivityDelegate.java, projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/container/PluginContainerActivity.java
PluginActivity 接收不到 onKeyUp/onKeyDown 事件，所以将这部分逻辑补上了。
=> 添加 activity onKeyUp/onKeyDown 回调

buildScripts/gradle/maven.gradle
将编译的产物发布到 maven 库中时会附上 java/kotlin 源文件。
close #121
=> add maven publish with sources

projects/sample/maven/host-project/build.gradle, projects/sample/maven/manager-project/build.gradle, projects/sample/maven/plugin-project/build.gradle, projects/sample/maven/plugin-project/sample-loader/src/main/java/com/tencent/shadow/sample/loader/SamplePluginLoader.java, projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ShadowContext.java
1. ./gradlew publish 报一处lint检查api版本错误
1. 因为Reporter接口基本没实现，所以从SDK中删除了。Maven Sample中忘记同步修改了。
fix #141 
fix #142
=> 修复Maven Sample的编译问题

projects/sdk/core/transform/src/main/kotlin/com/tencent/shadow/core/transform/specific/DialogTransform.kt, projects/sdk/core/transform/src/test/java/android/app/Dialog.java, projects/sdk/core/transform/src/test/java/com/tencent/shadow/core/runtime/ShadowActivity.java, projects/sdk/core/transform/src/test/java/com/tencent/shadow/core/runtime/ShadowDialog.java, projects/sdk/core/transform/src/test/java/test/dialog/BarDialog.java, projects/sdk/core/transform/src/test/java/test/dialog/Foo.java, projects/sdk/core/transform/src/test/kotlin/com/tencent/shadow/core/transform/specific/DialogTransformTest.kt
review #134 时写了单元测试。发现#134 发现的问题时存在的，但是修复代码没能修复问题。
=> 修复DialogTransform的getOwnerActivity、setOwnerActivity转换失败的问题

projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ShadowFactory2.java
=> ShadowFactory2的sConstructorMap应该是static的

projects/sample/source/sample-host/src/main/AndroidManifest.xml, projects/sample/source/sample-plugin/sample-app-lib/src/main/AndroidManifest.xml, projects/sample/source/sample-plugin/sample-app-lib/src/main/assets/web/test.html, projects/sample/source/sample-plugin/sample-app-lib/src/main/java/com/tencent/shadow/sample/plugin/app/lib/gallery/cases/UseCaseManager.java, projects/sample/source/sample-plugin/sample-app-lib/src/main/java/com/tencent/shadow/sample/plugin/app/lib/usecases/webview/WebViewActivity.java, projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/blocs/CreateResourceBloc.kt, projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ShadowWebView.java
1. 修复当WebView加载file:///android_asset/类型URL带有?参数时不能加载的问题
2.修复WebView中使用select标签会Crash的问题
3.以上两种场景在sample.source中添加一个手工测试用例
=> 修复WebView的两个问题

projects/sample/maven/host-project/introduce-shadow-lib/src/main/java/com/tencent/shadow/sample/introduce_shadow_lib/InitApplication.java, projects/sample/source/sample-host/src/main/java/com/tencent/shadow/sample/host/HostApplication.java, projects/sample/sunflower/host-project/introduce-shadow-lib/src/main/java/com/tencent/shadow/sample/introduce_shadow_lib/InitApplication.java
=> test(sample): 修复sample中recoveryRuntime的错误

projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/blocs/CreateApplicationBloc.kt, projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/managers/PluginServiceManager.kt, projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ShadowContext.java
添加对getPackageName()支持，不论宿主和插件的包名是否一致，都能保证获取的是插件的包名
=> feat(): 支持getPackageName()方法

buildScripts/gradle/common.gradle, projects/sample/maven/host-project/gradle.properties, projects/sample/maven/manager-project/gradle.properties, projects/sample/maven/plugin-project/gradle.properties, projects/sample/sunflower/host-project/gradle.properties, projects/sample/sunflower/manager-project/gradle.properties, projects/sample/sunflower/plugin-project/gradle.properties, projects/sdk/core/activity-container/src/main/java/com/tencent/shadow/core/runtime/container/HostActivityDelegator.java, projects/sdk/core/gradle-plugin/src/test/testProjects/case1/build.gradle, projects/sdk/core/gradle-plugin/src/test/testProjects/case1/plugin1/build.gradle, projects/sdk/core/gradle-plugin/src/test/testProjects/case1/plugin2/build.gradle, projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ShadowActivity.java, projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ShadowActivityLifecycleCallbacks.java, projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ShadowApplication.java, projects/sdk/dynamic/dynamic-loader-impl/src/main/kotlin/com/tencent/shadow/dynamic/loader/impl/PluginLoaderBinder.kt
=> Compile SDK升级到29，支持api 29新增的Activity方法registerActivityLifecycleCallbacks

projects/test/none-dynamic/host/test-none-dynamic-host/src/main/java/com/tencent/shadow/test/none_dynamic/host/HostApplication.java, projects/test/none-dynamic/host/test-none-dynamic-host/src/main/java/com/tencent/shadow/test/none_dynamic/host/MainActivity.java
主线程loadplugin会触发对CreateResourceBloc#create方法的等待，造成死锁
=> 修复test-none-dynamic-host工程loadplugin中初始化webview导致的死锁问题

projects/test/none-dynamic/host/test-none-dynamic-host/src/main/java/com/tencent/shadow/test/none_dynamic/host/HostApplication.java, projects/test/none-dynamic/host/test-none-dynamic-host/src/main/java/com/tencent/shadow/test/none_dynamic/host/MainActivity.java, projects/test/none-dynamic/host/test-none-dynamic-host/src/main/java/com/tencent/shadow/test/none_dynamic/host/TestComponentManager.java, projects/test/plugin/general-cases/general-cases-lib/src/main/AndroidManifest.xml, projects/test/plugin/general-cases/general-cases-lib/src/main/java/com/tencent/shadow/test/plugin/general_cases/lib/usecases/activity/TestListActivity.java, projects/test/plugin/general-cases/general-cases-lib/src/main/res/layout/activity_list.xml, projects/test/plugin/general-cases/general-cases-lib/src/main/res/layout/layout_list_item.xml
修复HostApplication中多次loadPlugin导致的crash，修改测试入口activity，动态列出所有插件activity
=> test(test-none-dynamic-host):修复插件多次加载导致的crash,更新入口activity

projects/sdk/core/activity-container/src/main/java/android/app/TaskStackBuilder.java
通过https://developer.android.com/sdk/api_diff/16/changes找出新增的接口涉及的新类型
#230
=> fix(activity-container): 添加API16引入的类型的假定义

projects/sample/source/sample-manager/src/main/java/com/tencent/shadow/sample/manager/FastPluginManager.java, projects/sdk/core/manager/src/androidTest/java/com/tencent/shadow/core/manager/installplugin/DbCompatibilityTest.java, projects/sdk/core/manager/src/main/java/com/tencent/shadow/core/manager/BasePluginManager.java, projects/sdk/core/manager/src/main/java/com/tencent/shadow/core/manager/installplugin/CopySoBloc.java, projects/sdk/core/manager/src/main/java/com/tencent/shadow/core/manager/installplugin/InstalledDao.java, projects/sdk/core/manager/src/main/java/com/tencent/shadow/core/manager/installplugin/InstalledPlugin.java, projects/sdk/core/manager/src/main/java/com/tencent/shadow/core/manager/installplugin/InstalledRow.java, projects/sdk/core/manager/src/main/java/com/tencent/shadow/core/manager/installplugin/ODexBloc.java, projects/sdk/core/manager/src/main/java/com/tencent/shadow/core/manager/installplugin/PluginConfig.java, projects/test/dynamic/manager/test-dynamic-manager/src/main/java/com/tencent/shadow/test/dynamic/manager/FastPluginManager.java
之前插件安装时在是分成3次更新数据库条目的。在所有更新操作完成前如果程序中断，会导致数据库中产生不正确的脏数据。尤其可能导致不完整数据的插件在启动时找不到so文件。
fix #259
=> fix(core.manager): 安装插件时在所有IO操作完成后一次性写入数据库(#259)

projects/sdk/core/manager/src/androidTest/java/com/tencent/shadow/core/manager/installplugin/SafeZipInputStreamTest.java
=> test(core.manager): 添加一个SafeZipInputStream的单元测试类

projects/sdk/core/manager/build.gradle, projects/sdk/core/manager/src/androidTest/java/com/tencent/shadow/core/manager/installplugin/CopySoBlocTest.java, projects/sdk/core/manager/src/androidTest/java/common/AndroidLogLoggerFactory.java
=> test(core.manager): 添加一个手工测试CopySoBloc的单元测试类

projects/sdk/core/activity-container/src/main/java/com/tencent/shadow/core/runtime/container/PluginContainerActivity.java
=> fix(core.runtime): IllegalIntent时同时置空super.hostActivityDelegate

projects/sample/maven/host-project/build.gradle, projects/sample/maven/host-project/introduce-shadow-lib/build.gradle, projects/sample/maven/host-project/sample-host/build.gradle, projects/sample/maven/manager-project/build.gradle, projects/sample/maven/manager-project/sample-manager/build.gradle, projects/sample/maven/manager-project/sample-manager/src/main/java/com/tencent/shadow/sample/manager/FastPluginManager.java, projects/sample/maven/plugin-project/build.gradle, projects/sample/maven/plugin-project/plugin-main-lib/build.gradle, projects/sample/maven/plugin-project/plugin-normal-apk/build.gradle, projects/sample/maven/plugin-project/sample-loader/build.gradle, projects/sample/maven/plugin-project/sample-runtime/build.gradle, projects/sample/sunflower/host-project/build.gradle, projects/sample/sunflower/host-project/introduce-shadow-lib/build.gradle, projects/sample/sunflower/host-project/sample-host/build.gradle, projects/sample/sunflower/manager-project/build.gradle, projects/sample/sunflower/manager-project/sample-manager/build.gradle, projects/sample/sunflower/manager-project/sample-manager/src/main/java/com/tencent/shadow/sample/manager/FastPluginManager.java, projects/sample/sunflower/plugin-project/app/build.gradle, projects/sample/sunflower/plugin-project/build.gradle, projects/sample/sunflower/plugin-project/sample-loader/build.gradle, projects/sample/sunflower/plugin-project/sample-runtime/build.gradle
=> test(sample): 修复maven和sunflower两个sample编译问题 

README.md
=> docs: 建议使用3.5以上版本的Android Studio

projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ContainerDialogFragment.java, projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ContainerFragment.java, projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ShadowFragment.java, projects/test/dynamic/host/test-dynamic-host/src/androidTest/java/com/tencent/shadow/test/cases/plugin_main/TargetFragmentTest.java, projects/test/plugin/general-cases/general-cases-lib/src/main/AndroidManifest.xml, projects/test/plugin/general-cases/general-cases-lib/src/main/java/com/tencent/shadow/test/plugin/general_cases/lib/usecases/fragment/TargetFragmentTestActivity.java
=> feat(fragment): 支持Fragment的setTargetFragment方法

buildScripts/gradle/common.gradle
添加环境检查，优化错误提示。之前若不存在sdk时，报错信息无法帮助开发者定位到问题
关联 issue #355
=> 添加环境检查，优化错误提示

buildScripts/gradle/common.gradle
避免Windows下提示路径不正确的问题。
!fixup 65b95750
#435
=> chore: 重构android.jar路径提示

projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/PluginActivity.java, projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ShadowActivity.java
=> 修复直接实例化Activity报java.lang.InstantiationError的错误

projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/blocs/LoadPluginBloc.kt, projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/managers/PluginPackageManagerImpl.kt, projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/PackageManagerInvokeRedirect.java, projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/PluginPackageManager.java, projects/sdk/core/transform/src/main/kotlin/com/tencent/shadow/core/transform/specific/PackageManagerTransform.kt, projects/test/dynamic/host/test-dynamic-host/src/androidTest/java/com/tencent/shadow/test/cases/plugin_main/PackageManagerTest.java, projects/test/plugin/general-cases/general-cases-app/build.gradle, projects/test/plugin/general-cases/general-cases-app/src/androidTest/java/com/tencent/shadow/test/plugin/general_cases/app/CustomAndroidJUnitRunner.java, projects/test/plugin/general-cases/general-cases-app/src/androidTest/java/com/tencent/shadow/test/plugin/general_cases/app/NormalAppTest.java, projects/test/plugin/general-cases/general-cases-app/src/androidTest/java/com/tencent/shadow/test/plugin/general_cases/app/PackageManagerTest.java, projects/test/plugin/general-cases/general-cases-lib/src/main/AndroidManifest.xml, projects/test/plugin/general-cases/general-cases-lib/src/main/java/com/tencent/shadow/test/plugin/general_cases/lib/usecases/packagemanager/TestPackageManagerActivity.java
=> 支持queryContentProviders和resolveActivity使用显式Intent

projects/sample/maven/host-project/build.gradle, projects/sample/maven/manager-project/build.gradle, projects/sample/maven/plugin-project/build.gradle, projects/sample/maven/plugin-project/plugin-shadow-apk/build.gradle, projects/sample/sunflower/host-project/build.gradle, projects/sample/sunflower/manager-project/build.gradle, projects/sample/sunflower/plugin-project/build.gradle
=> test: sample改为依赖2.1.0正式版本

projects/sdk/core/transform-kit/src/main/kotlin/com/tencent/shadow/core/transform_kit/JavassistTransform.kt
fix transform中输入过程inputStream使用后没有关闭的问题,会导致内存泄漏
=> fix transform中输入过程inputStream使用后没有关闭的问题

buildScripts/gradle/maven.gradle
=> build: core.utils补充maven发布配置

projects/test/dynamic/host/test-dynamic-host/src/androidTest/java/com/tencent/shadow/test/cases/plugin_androidx/ComponentFactoryTest.java, projects/test/plugin/androidx-cases/androidx-cases-lib/src/main/AndroidManifest.xml, projects/test/plugin/androidx-cases/androidx-cases-lib/src/main/java/com/tencent/shadow/test/plugin/androidx_cases/lib/AppComponentFactoryTestActivity.java, projects/test/plugin/androidx-cases/androidx-cases-lib/src/main/java/com/tencent/shadow/test/plugin/androidx_cases/lib/TestComponentFactory.java
=> test: 添加appComponentFactory测试用例

projects/sample/source/sample-host/src/main/AndroidManifest.xml, projects/sample/source/sample-plugin/sample-loader/src/main/java/com/tencent/shadow/sample/plugin/loader/SampleComponentManager.java, projects/test/dynamic/host/test-dynamic-host/src/main/AndroidManifest.xml, projects/test/dynamic/plugin/test-dynamic-loader/src/main/java/com/tencent/shadow/test/dynamic/loader/TestComponentManager.java
=> fix: sample和test宿主app的provider authorities使用applicationId区分开

projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/managers/PluginServiceManager.kt, projects/test/dynamic/host/test-dynamic-host/src/androidTest/java/com/tencent/shadow/test/cases/plugin_main/PluginServiceTest.java, projects/test/plugin/general-cases/general-cases-lib/src/main/java/com/tencent/shadow/test/plugin/general_cases/lib/usecases/service/TestStartServiceActivity.java, projects/test/plugin/general-cases/general-cases-lib/src/main/res/layout/layout_service.xml
=> fix(core.loader): 固定在主线程调用插件Service生命方法

projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/managers/ComponentManager.kt, projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/managers/PluginServiceManager.kt
=> fix(core.loader): 修复无法unbind非插件Service的问题

.github/workflows/pr-check.yml, .github/workflows/release.yml
ReactiveCircus/android-emulator-runner#160
=> ci: fix android test

projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ShadowActivityLifecycleCallbacks.java, projects/test/plugin/general-cases/general-cases-lib/src/main/java/com/tencent/shadow/test/plugin/general_cases/lib/gallery/TestApplication.java
=> fix(core.runtime): notifyPluginActivityPreCreated时先复制一份callback再for-each

projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ShadowFragmentSupport.java, projects/sdk/core/transform/src/main/kotlin/com/tencent/shadow/core/transform/specific/FragmentSupportTransform.kt, projects/sdk/core/transform/src/test/java/android/app/Fragment.java, projects/sdk/core/transform/src/test/java/com/tencent/shadow/core/runtime/ShadowFragmentSupport.java, projects/sdk/core/transform/src/test/java/test/fragment/UseStartActivityForResultFragment.java, projects/sdk/core/transform/src/test/kotlin/com/tencent/shadow/core/transform/specific/FragmentSupportTransformTest.kt
=> feat(core): support Fragment.startActivityForResult

projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ShadowApplication.java, projects/test/dynamic/host/test-dynamic-host/src/androidTest/java/com/tencent/shadow/test/cases/plugin_main/ApplicationTest.java, projects/test/plugin/general-cases/general-cases-lib/src/main/java/com/tencent/shadow/test/plugin/general_cases/lib/usecases/application/TestApplicationActivity.java
=> fix(core.runtime): 支持Application.getProcessName()方法

projects/sample/maven/host-project/build.gradle, projects/sample/maven/manager-project/build.gradle, projects/sample/maven/plugin-project/build.gradle, projects/sample/sunflower/host-project/build.gradle, projects/sample/sunflower/manager-project/build.gradle, projects/sample/sunflower/plugin-project/build.gradle
=> chore: 升级maven sample依赖Shadow版本到2.1.1

projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ShadowService.java
=> [fix] 增加 ShadowService::startForeground(int, Notification, int)

projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/classloaders/PluginClassLoader.kt
=> fix(core.loader): 像普通ClassLoader一样优先findLoadedClass

projects/sample/source/sample-plugin/sample-loader/src/main/java/com/tencent/shadow/sample/plugin/loader/SampleComponentManager.java, projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/blocs/CreateApplicationBloc.kt, projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/blocs/LoadPluginBloc.kt, projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/blocs/ParseManifestBloc.kt, projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/blocs/ParsePluginApkBloc.kt, projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/infos/ManifestInfo.kt, projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/infos/PluginInfo.kt, projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/infos/PluginReceiverInfo.kt, projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/managers/ComponentManager.kt, projects/test/dynamic/plugin/test-dynamic-loader/src/main/java/com/tencent/shadow/test/dynamic/loader/TestComponentManager.java, projects/test/none-dynamic/host/test-none-dynamic-host/src/main/java/com/tencent/shadow/test/none_dynamic/host/TestComponentManager.java
fix(core.loader): 支持AndroidManifest解析,针对广播解析Action信息,代替ComponentManager手动配置的逻辑
=>  fix(core.loader): 支持AndroidManifest解析,针对广播解析Action信息,代替ComponentManager手动配置的逻辑

.github/workflows/release.yml
=> ci: 修复release构建缺少VERSION_NAME的问题

.github/workflows/pr-check.yml
=> ci: 修复build-samples中的gradle wrapper还原

projects/sdk/core/manager/src/main/java/com/tencent/shadow/core/manager/BasePluginManager.java
=> fix(core.manager): partKey不正确时及时抛出异常

README.md, settings.gradle
=> build: 自动复制local.properties到includeBuild目录

projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/FixedContextLayoutInflater.java, projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ShadowWebViewLayoutInflater.java
=> refactor(core.runtime): 改进FixedContextLayoutInflater的代码可读性

projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/managers/PluginServiceManager.kt
利用@Suppress("UNCHECKED_CAST")检查感觉不太符合kotlin化，可以考虑利用reified避免泛型擦除后的类型验证问题，在编译时解决
=> perf:删除依靠 @Suppress("UNCHECKED_CAST")检查

buildScripts/gradle/maven.gradle, projects/sdk/core/gradle-plugin/src/main/kotlin/com/tencent/shadow/core/gradle/ShadowPlugin.kt, projects/sdk/core/manifest-parser/build.gradle, projects/sdk/core/manifest-parser/src/main/kotlin/com/tencent/shadow/core/manifest_parser/PluginManifestGenerator.kt
=> 修复PluginManifest与低版本AGP兼容性的Bug

projects/sdk/coding/get-android-jar/build.gradle
=> chore: 没有安装所需Android SDK时给出明确提示

projects/sdk/dynamic/dynamic-loader-impl/src/main/kotlin/com/tencent/shadow/dynamic/loader/impl/DynamicPluginLoader.kt
一些值得format kt code
cast操作内部其实已经强转为T，直接as保证逻辑不空
=> perf:format

.github/workflows/pr-check-gradle-plugin.yml, projects/sdk/core/transform-kit/src/main/kotlin/com/tencent/shadow/core/transform_kit/ClassTransform.kt, projects/test/gradle-plugin-agp-compat-test/test.sh
=> feat: 支持消费Shadow时使用Gradle 7.2与AGP 7.1.1

projects/test/gradle-plugin-agp-compat-test/stub-project/build.gradle, projects/test/gradle-plugin-agp-compat-test/test.sh
=> test: 测试插件项目存在自定义flavorDimensions

projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/managers/PluginPackageManagerImpl.kt, projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/PluginPackageManager.java, projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ShadowContext.java, projects/test/dynamic/host/test-dynamic-host/src/androidTest/java/com/tencent/shadow/test/cases/plugin_main/ContextGetPackageCodePathTest.java, projects/test/plugin/general-cases/test-plugin-general-cases/src/main/AndroidManifest.xml, projects/test/plugin/general-cases/test-plugin-general-cases/src/main/java/com/tencent/shadow/test/plugin/general_cases/lib/usecases/context/ContextGetPackageCodePathTestActivity.java
=> feat(core.loader): 支持Context.getPackageCodePath

projects/sdk/dynamic/dynamic-host/src/main/java/com/tencent/shadow/dynamic/host/PluginManager.java
=> chore(dynamic.dynamic-host): fix typo

projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/delegates/ShadowActivityDelegate.kt, projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/BroadcastReceiverWrapper.java, projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/PluginActivity.java, projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ShadowActivityLifecycleCallbacks.java, projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ShadowApplication.java, projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ShadowContext.java
=> 修复两处Wrapper对象Map造成的内存泄漏风险

projects/sdk/core/manager/src/main/java/com/tencent/shadow/core/manager/BasePluginManager.java, projects/sdk/core/manager/src/main/java/com/tencent/shadow/core/manager/installplugin/InstalledDao.java
=> fix(core.manager): 查询最新安装的插件时以改为自增ID为依据

buildScripts/gradle/common.gradle, projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/managers/ComponentManager.kt, projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/managers/PluginPackageManagerImpl.kt, projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/PackageManagerInvokeRedirect.java, projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/PluginPackageManager.java, projects/sdk/core/transform/src/main/kotlin/com/tencent/shadow/core/transform/specific/PackageManagerTransform.kt, projects/test/dynamic/host/test-dynamic-host/src/androidTest/java/com/tencent/shadow/test/cases/plugin_main/PackageManagerTest.java, projects/test/plugin/androidx-cases/test-plugin-androidx-cases/build.gradle, projects/test/plugin/general-cases/test-plugin-general-cases/src/androidTest/java/com/tencent/shadow/test/plugin/general_cases/app/PackageManagerTest.java, projects/test/plugin/general-cases/test-plugin-general-cases/src/main/java/com/tencent/shadow/test/plugin/general_cases/lib/usecases/packagemanager/TestPackageManagerActivity.java
以便自动生成31新增的Activity方法，使新版本第三方SDK如androidx等不会因为找不到新方法而编译失败。
close #868
=> feat: 升级compileSdkVersion到31

projects/test/dynamic/host/test-dynamic-host/src/androidTest/java/com/tencent/shadow/test/cases/plugin_main/ActivityLifecycleCallbacksTest.java, projects/test/dynamic/host/test-dynamic-host/src/androidTest/java/com/tencent/shadow/test/cases/plugin_main/application_info/PackageManagerGetOtherInstalledApplicationInfoTest.java, projects/test/plugin/general-cases/test-plugin-general-cases/src/androidTest/java/com/tencent/shadow/test/plugin/general_cases/app/ActivityLifecycleCallbacksTest.java, projects/test/plugin/general-cases/test-plugin-general-cases/src/main/java/com/tencent/shadow/test/plugin/general_cases/lib/usecases/application/TestGetApplicationInfoActivity.java, projects/test/plugin/general-cases/test-plugin-general-cases/src/main/java/com/tencent/shadow/test/plugin/general_cases/lib/usecases/dialog/TestAlertDialogActivity.java, projects/test/plugin/general-cases/test-plugin-general-cases/src/main/java/com/tencent/shadow/test/plugin/general_cases/lib/usecases/dialog/TestDialogActivity.java, projects/test/plugin/general-cases/test-plugin-general-cases/src/main/java/com/tencent/shadow/test/plugin/general_cases/lib/usecases/instrumentation/TestInstrumentationActivity.java
=> 在API 16虚拟机上跑全量测试，修复部分测试用例

projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/managers/PluginPackageManagerImpl.kt
=> fix(core.loader): PluginPackageManagerImpl支持宿主requestedPermissions属性传递

projects/sample/source/sample-plugin/sample-base-lib/src/main/java/com/tencent/shadow/sample/plugin/app/lib/gallery/cases/UseCaseSummaryFragment.java, projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ActivityOptionsSupport.java, projects/sdk/core/transform/build.gradle, projects/sdk/core/transform/src/main/kotlin/com/tencent/shadow/core/transform/TransformManager.kt, projects/sdk/core/transform/src/main/kotlin/com/tencent/shadow/core/transform/specific/ActivityOptionsSupportTransform.kt
只简单测试了ActivityOptionsSupport中的转调方法可以被断点到，确定转调正常。
fix #976
=> feat(core): 支持ActivityOptions.makeSceneTransitionAnimation

projects/sdk/core/transform-kit/src/main/kotlin/com/tencent/shadow/core/transform_kit/SpecificTransform.kt, projects/sdk/core/transform-kit/src/test/java/test/override/Foo.java, projects/sdk/core/transform-kit/src/test/kotlin/com/tencent/shadow/core/transform_kit/FilterRefClassesTest.kt, projects/sdk/core/transform/src/main/kotlin/com/tencent/shadow/core/transform/specific/SimpleRenameTransform.kt
=> perf(core.transform): 避免allInputClass作为filter

projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/blocs/CreateResourceBloc.kt, projects/test/dynamic/host/test-dynamic-host/src/androidTest/java/com/tencent/shadow/test/cases/plugin_main/NullRefInXmlTest.java, projects/test/plugin/general-cases/test-plugin-general-cases/src/main/AndroidManifest.xml, projects/test/plugin/general-cases/test-plugin-general-cases/src/main/java/com/tencent/shadow/test/plugin/general_cases/lib/usecases/view/TestNullRefInXmlActivity.java, projects/test/plugin/general-cases/test-plugin-general-cases/src/main/res/layout/layout_test_null_ref.xml
=> fix(core.loader): API小于等于27时采用MixResource方案

build.gradle, buildScripts/gradle/common.gradle, projects/sample/maven/host-project/build.gradle, projects/sample/maven/manager-project/build.gradle, projects/sample/maven/plugin-project/build.gradle, projects/sample/maven/plugin-project/plugin-app/build.gradle, projects/sample/source/sample-plugin/sample-app/build.gradle, projects/sample/source/sample-plugin/sample-base/build.gradle, projects/sdk/coding/build.gradle, projects/sdk/coding/common-jar-settings/build.gradle, projects/sdk/coding/java-build-config/build.gradle, projects/sdk/core/build.gradle, projects/sdk/core/gradle-plugin/src/main/kotlin/com/tencent/shadow/core/gradle/ShadowPlugin.kt, projects/sdk/core/gradle-plugin/src/test/testProjects/case1/build.gradle, projects/sdk/core/gradle-plugin/src/test/testProjects/case1/plugin1/build.gradle, projects/sdk/core/gradle-plugin/src/test/testProjects/case1/plugin2/build.gradle, projects/sdk/dynamic/build.gradle, projects/test/gradle-plugin-agp-compat-test/stub-project/build.gradle, projects/test/gradle-plugin-agp-compat-test/stub-project/src/main/java/PluginManifestIncludeTest.java, projects/test/gradle-plugin-agp-compat-test/test.sh, projects/test/plugin/androidx-cases/test-plugin-androidx-cases/build.gradle, projects/test/plugin/general-cases/test-plugin-general-cases/build.gradle, projects/test/plugin/particular-cases/plugin-service-for-host/build.gradle
改正前只有在AGP低至3.2.0或高至7.2.2才会出现问题。
改正方法是基于调试得出，未能查到两种方法区别的理论依据。由于有自动化测试验证，故放心修改。
fix #1074
fix #1047
=> fix(core.gradle-plugin): 改正添加PluginManifest.java到源码路径的实现

projects/sdk/dynamic/dynamic-host-multi-loader-ext/src/main/java/com/tencent/shadow/dynamic/host/MultiDynamicContainer.java
由于多个plugin的加载顺序不固定，所以一般应该是都打包了core.runtime.container的。 如果双亲委派的话，肯定容易出现不同plugin的Activity壳子子类和父类在不同ClassLoader的情况。
子类和父类在不同的ClassLoader会触发HasSameSignatureWithDifferentClassLoaders的校验， 使得本来不调用就不会被加载的新版本API新增类型（如ContextParams）被加载，从而在低版本机型上找不到类。
fix #1118
=> MultiDynamicContainer的ClassLoader去掉双亲委派逻辑

projects/sample/maven/host-project/introduce-shadow-lib/src/main/java/com/tencent/shadow/sample/introduce_shadow_lib/InitApplication.java, projects/sample/source/sample-host/src/main/java/com/tencent/shadow/sample/host/HostApplication.java, projects/test/dynamic/host/test-dynamic-host/src/main/java/com/tencent/shadow/test/dynamic/host/HostApplication.java
=> test(sample): sample中插件进程不该重复执行主进程才该执行的初始化流程

projects/sample/source/sample-plugin/sample-app/src/main/java/com/tencent/shadow/sample/plugin/app/lib/usecases/receiver/TestDynamicReceiverActivity.java
=> fix(sample): 大于API 33，广播插件case，运行崩溃

projects/sample/source/sample-host/src/main/java/com/tencent/shadow/sample/host/PluginHelper.java
=> fix: sample-host更新manager.apk时需要先设置可写入
